//
//  NewsDetailInteractor.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsDetailInteractor {

    weak var presenter: NewsDetailPresenterProtocol?
}

extension NewsDetailInteractor: NewsDetailInteractorProtocol {
    
}
