//
//  NewsDetailPresenter.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsDetailPresenter {

    weak private var view: NewsDetailViewProtocol?
    var interactor: NewsDetailInteractorProtocol?
    private let router: NewsDetailWireframeProtocol

    init(interface: NewsDetailViewProtocol, interactor: NewsDetailInteractorProtocol?, router: NewsDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension NewsDetailPresenter: NewsDetailPresenterProtocol {
    
    func notifyDisplayNewsDetail(news: ArticlesEntity) {
        self.view?.displayNewsDetail(news: news)
    }
    
    func notifyRouteToMain() {
        self.router.routeToMain()
    }
    
}
