//
//  NewsDetailRouter.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsDetailRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = NewsDetailViewController(nibName: nil, bundle: nil)
        let interactor = NewsDetailInteractor()
        let router = NewsDetailRouter()
        let presenter = NewsDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    static func createModuleNewsData(news: ArticlesEntity) -> UIViewController {
        let view = NewsDetailRouter.createModule() as! NewsDetailViewController
        
        view.presenter?.notifyDisplayNewsDetail(news: news)
        
        return view
    }
    
}

extension NewsDetailRouter: NewsDetailWireframeProtocol {
    
    func routeToMain() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
}
