//
//  NewsDetailProtocols.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NewsDetailWireframeProtocol: class {
    func routeToMain()
}
//MARK: Presenter -
protocol NewsDetailPresenterProtocol: class {
    func notifyDisplayNewsDetail(news: ArticlesEntity)
    func notifyRouteToMain()
}

//MARK: Interactor -
protocol NewsDetailInteractorProtocol: class {
    var presenter: NewsDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol NewsDetailViewProtocol: class {
    var presenter: NewsDetailPresenterProtocol?  { get set }
    func displayNewsDetail(news: ArticlesEntity)
}
