//
//  MainInteractor.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainInteractor {

    weak var presenter: MainPresenterProtocol?
}

extension MainInteractor: MainInteractorProtocol {
    
    func fetchNewsData() {
        NewsAPIHelper.sharedInstance().fetchNewsAPI { statusFetchNewsAPI in
            if statusFetchNewsAPI == "ok" {
                if let newsData = UserSession.shared.getNewsData() {
                    self.presenter?.notifyDisplayNewsData(newsData: newsData)
                }
            } else {
                print("error fetch data")
            }
        }
    }
    
}
