//
//  MainPresenter.swift
//  news_app
//
//  Created Phattarapon Jungtakarn on 22/7/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPresenter {

    weak private var view: MainViewProtocol?
    var interactor: MainInteractorProtocol?
    private let router: MainWireframeProtocol

    init(interface: MainViewProtocol, interactor: MainInteractorProtocol?, router: MainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension MainPresenter: MainPresenterProtocol {
    
    func notifyFetchNewsData() {
        self.interactor?.fetchNewsData()
    }
    
    func notifyDisplayNewsData(newsData: NewsEntity) {
        self.view?.displayNewsData(newsData: newsData)
    }
    
    func notifyRouteToDetailView(news: ArticlesEntity) {
        self.router.routeToDetailView(news: news)
    }
    
}
